// content.js — single bilingual source for the deck (build_deck.js) and the memo (build_doc.js).
// Every number here must appear in docs/SOURCES.md.

const C = {
  en: {
    font: { head: "Cambria", body: "Calibri" },
    file: "gstack-tutorial-5",
    // ---------------- deck ----------------
    deck: {
      title: "From YouTube analytics to a re-engineered Short",
      kicker: "gstack Tutorial #5",
      subtitle: "CSR-RAP agent × Claude Opus 5.5 × HyperFrames — how the AGI Race V2 was made",
      scope: "Scope: V2 of the published AGI Race Short. Episode 2 (Mission: Impossible) is still in production and is not taught here.",
      date: "September 2026",
      exec: {
        title: "V2 raised structural quality by 27.9 %; whether viewers agree is still an open test",
        cards: [
          { big: "0.602 → 0.770", label: "CSR-RAP B score", text: "V1 proved the topic (R × A). V2 adds the production system (R × P = 0.865)." },
          { big: "4.15 s", label: "Hook complete", text: "Punchline first, title second: the premise lands in 8.9 % of the Short." },
          { big: "1.67 → ?", label: "Comments per 1,000 views", text: "Target > 2.5. Nothing is proven until 72 h of real V2 analytics return." },
        ],
      },
      system: {
        title: "The leverage came from splitting the work across three systems with different jobs",
        takeaway: "Decide (CSR-RAP) → build (Opus 5.5 + gstack) → render (HyperFrames) → measure, then loop.",
      },
      model: {
        title: "Generative AI creates uncertain pixels; HyperFrames controls certain information",
        left: "Must be exactly right → HyperFrames",
        leftItems: ["Timing of every beat, to the frame", "All on-screen text, captions, role tags", "9:16 reframing per shot", "Freeze, black cut, end-card", "Audio cue placement"],
        right: "May vary → generative model / source footage",
        rightItems: ["Photoreal characters and environments", "Motion inside a shot", "Texture and lighting detail"],
        test: "Seek-safe test: if the renderer jumps straight to t = 4.312 s, is the frame still correct?",
        note: "V2 needed almost nothing from the right column: its pixels already existed in V1.",
      },
      setup: {
        title: "The whole toolchain installs on Windows 11 in about 10 minutes; gstack takes one",
        steps: [
          { n: "1", h: "Prerequisites", t: "Git · Node.js ≥ 22 · FFmpeg · Bun ≥ 1.0 · Claude Code", code: "winget install --id OpenJS.NodeJS -e" },
          { n: "2", h: "gstack (~1 min)", t: "Paste the README one-liner into Claude Code; test with /office-hours", code: "git clone … garrytan/gstack.git ~/.claude/skills/gstack && ./setup" },
          { n: "3", h: "HyperFrames", t: "Install the Claude Code plugin; restart; /hyperframes routes the job", code: "claude plugin install hyperframes@hyperframes" },
          { n: "4", h: "Doctor first", t: "Check the machine before designing anything; pin the CLI version", code: "npx hyperframes doctor" },
        ],
        pitfall: "Pitfall we hit: 'claude' is not recognized → add %LOCALAPPDATA%\\Microsoft\\WinGet\\Links to PATH and open a new PowerShell.",
      },
      shot: {
        title: "Two commands install HyperFrames; the doctor check runs before any design work",
        caption: "Illustrative mock-up with annotations. Replace with your own screenshot.",
      },
      diag: {
        title: "V1 proved the topic works, but conversion did not follow the views",
        stats: [
          { big: "58,736", label: "views (channel's first breakout)" },
          { big: "98", label: "comments" },
          { big: "1.67", label: "CCI = comments per 1,000 views" },
        ],
        rows: [["R  Rules of Business", "88", "Cognitive compression: an AI race became a desert race"],
               ["A  Attributes of Industry", "90", "Hot topic, recognisable figures, strong Shorts fit"],
               ["P  Production capability", "76", "Weak causality; fails in 9:16"],
               ["B = R × A × P", "0.602", "One weak layer caps the whole result"]],
        head: ["Layer", "Score", "Diagnosis"],
      },
      dna: {
        title: "Measuring V1 first showed what to keep and exactly what broke on mobile",
        stats: [
          { big: "62.49 s", label: "runtime" },
          { big: "47", label: "shots (46 hard cuts)" },
          { big: "1.08 s", label: "median shot; 20 of 46 under 1 s" },
          { big: "0.95 s", label: "mean shot in the fastest block, just before the climax" },
          { big: "1.5 s + 0.84 s", label: "near-freeze, then black" },
          { big: "4", label: "elements cut by a 9:16 crop: title, ensemble, final freeze, every subtitle" },
        ],
        note: "All values FFmpeg-measured by Opus 5.5 in Claude Code (Episode1_Visual_DNA.md).",
      },
      detour: {
        title: "An agent that only writes prompts for another generator is still gambling",
        quote: "“Entry gate: FAIL. Nothing has been generated yet… Numbers for frames nobody has generated would be invented.”",
        quoteBy: "Opus 5.5, text-to-video route, home PC",
        lessons: [
          { h: "The gate worked", t: "Opus refused to score footage that did not exist." },
          { h: "The dependency was wrong", t: "The pipeline waited on the least controllable step: generated faces." },
          { h: "The pivot proved the control layer", t: "C24 pilot: countdown correct at any seek time; black cut on frame 139; lint 0 errors; contrast 13/13." },
          { h: "…and showed its limit", t: "C24 scored R 0.82, A 0.75: held back by placeholder characters, not structure." },
        ],
      },
      playbook: {
        title: "Seven Shot Playbook rules turned one day's mistakes into permanent constraints",
        rules: [
          "Route through /hyperframes; multi-scene → /general-video",
          "Run doctor and read the timeline before designing",
          "Search the catalog before building; reuse components",
          "Seek-safe: no wall-clock logic, no Web Audio graphs, no conflicting fromTo",
          "Holds over ≈4 s get one monotonic micro-motion, never a loop",
          "Critical text in the centre third, so it survives 9:16",
          "lint → check → snapshot → render → ffprobe, then human eyes",
        ],
        note: "Renders are visually, not bit-for-bit, deterministic: 61 of 144 frames identical, the rest ≥ 50 dB PSNR.",
      },
      brief: {
        title: "The V2 brief pairs a change list from CSR-RAP with a keep list from the Visual DNA",
        left: "Change (from CSR-RAP)",
        leftItems: ["Cold open on the strongest punchline", "Title slam; hook complete by ≈4 s", "Role tags replace name recognition", "Delete unintelligible lines", "9:16 as its own composition", "End-card bridge to Episode 2"],
        right: "Keep (from Visual DNA)",
        rightItems: ["Fast grammar (median shot ≈1.08 s)", "Acceleration before the climax", "\"Slow down\" as the biggest close-up", "Unresolved jump", "Near-freeze → black ending", "Muted grade"],
        foot: "Before the build: /office-hours → /plan-ceo-review (scope: HOLD, re-edit only) → /plan-eng-review. After it: /review.",
      },
      timeline: {
        title: "V2 delivers spectacle, punchline and premise in the first 4.15 seconds",
      },
      map: {
        title: "Every V1 weakness the diagnosis named has a specific V2 answer",
        head: ["Metric", "V1", "V2", "Assessment"],
        rows: [
          ["Main runtime", "62.49 s", "56.34 s", "−9.8 %"],
          ["Short runtime", "—", "46.54 s", "−25.5 % vs V1"],
          ["Opening", "Lineup / title", "Strongest gag first", "Clear upgrade"],
          ["Hook complete", "Slower", "4.15 s", "Stronger"],
          ["Role comprehension", "Relies on recognition", "Explicit role tags", "Major upgrade"],
          ["9:16", "Fails in several places", "Shot-by-shot reframing", "Major upgrade"],
          ["Ending", "Unresolved jump", "Jump + Episode 2 bridge", "Commercial upgrade"],
          ["CTA system", "Weak / generic", "TO BE CONTINUED → EP 2 → SUBSCRIBE", "Clear upgrade"],
          ["Production", "Video generation", "Programmable HyperFrames re-edit", "P upgrade"],
        ],
      },
      rap: {
        title: "The strongest pair of layers moved from topic choice (R × A) to production system (R × P)",
        cats: ["R", "A", "P", "B"],
        v1: [88, 90, 76, 60.2], v2: [92, 89, 94, 77.0],
        callouts: [
          { big: "+27.9 %", t: "structural quality, B 0.602 → 0.770" },
          { big: "0.865", t: "R × P, now the strongest coupling, and it compounds across episodes" },
          { big: "≠ views", t: "a design score, not a forecast; A stays provisional until real data arrives" },
        ],
        chartTitle: "CSR-RAP score (×100)",
      },
      measure: {
        title: "Freeze both uploads for 72 hours and read three windows on the retention curve",
        head: ["Window", "Question", "If it fails"],
        rows: [
          ["0–4.15 s", "Does the cold open stop the swipe?", "Test another opening punchline"],
          ["≈40 s", "Does \"slow down → late entrant\" lift attention?", "Tighten the escalation before it"],
          ["Last 8.6 s", "Does the end-card add subscribers or cause exits?", "Cliff + no subscriber lift → hold 2.5 s → 1–1.5 s"],
        ],
        q: "The one question: does HyperFrames packaging turn the same content into better audience behaviour?",
        obs: "Observed RAP Score (proposed): hook = stayed-to-watch % · retention = APV · engagement = CCI (target > 2.5) · subscribers per 1,000 views · vertical advantage = Short APV ÷ master APV",
      },
      limits: {
        title: "Four limits stand between this result and a proven one",
        items: [
          { h: "No V2 analytics yet", t: "Every V2 claim is structural until the 72-hour pull." },
          { h: "Scores are judgements", t: "CSR-RAP rates design quality; it does not measure behaviour." },
          { h: "Generative layer untested", t: "Episode 2's faces, hands and keys remain the open risk." },
          { h: "Real people, satirised", t: "Role tags reduce reliance on likeness; review platform policy each release." },
        ],
      },
      os: {
        title: "The same nine steps re-engineer any Short, not just this one",
        steps: ["Export analytics; compute CCI", "Diagnose with CSR-RAP", "Measure: Visual DNA", "Challenge: /office-hours", "Brief Opus 5.5", "Build + verify in HyperFrames", "Re-score (design)", "Upload, freeze, measure 72 h", "Feed back into the next brief"],
      },
      close: {
        title: "Measure, don't re-edit",
        text: "The next decision belongs to the viewers' data, not to another render.",
        links: ["Repo: TUTORIAL.md · TUTORIAL.zh.md · starter/prompts · docs/SOURCES.md", "gstack: github.com/garrytan/gstack", "HyperFrames: github.com/heygen-com/hyperframes"],
      },
      sources: "Source: docs/SOURCES.md",
    },
    // ---------------- memo ----------------
    memo: {
      title: "Executive memo — gstack Tutorial #5",
      subtitle: "From YouTube analytics to a re-engineered Short: CSR-RAP × Claude Opus 5.5 × HyperFrames",
      meta: [["Subject", "How the AGI Race V2 was made, and what must happen next"], ["Date", "29 September 2026"], ["Companion files", "TUTORIAL.md (full tutorial) · slide deck · starter/prompts"]],
      h_bottom: "1. Bottom line",
      bottom: [
        "The leverage was not a better prompt. It was splitting the work across three systems with different jobs: a CSR-RAP agent decides what to change, Claude Opus 5.5 in Claude Code (with gstack) writes the change, and HyperFrames renders it deterministically.",
        "V2 re-engineers the published AGI Race Short (58,736 views, 98 comments). It opens on the strongest punchline, completes the hook by 4.15 s, replaces name recognition with role tags, re-directs every shot for 9:16, and ends on a bridge to Episode 2. Master 56.34 s (−9.8 %); Short 46.54 s (−25.5 %).",
        "CSR-RAP rates V2's structural quality at B = 0.770 against V1's 0.602 (+27.9 %). That is a design score. Whether viewers behave better is an open A/B test to be settled with 72 hours of real analytics.",
      ],
      h_scope: "2. Scope",
      scope: "This memo covers V2 of the existing AGI Race Short only. Episode 2 (“OpenAI vs. Anthropic — Mission: Impossible Edition”) is still in production and appears only where its pilot taught something about the production system.",
      h_system: "3. The system",
      system: "Each layer has one job and one thing it must never do. The strategy layer must not invent platform data; the agent layer must not merely write prompts for another generator; the render layer must not be asked to invent photoreal humans. The rule that governs the split is the seek-safe test: if the renderer jumps straight to any time, is the frame still correct? Everything that must be exactly right (timing, text, role tags, 9:16 crops, freezes, end-cards, audio cues) goes in HyperFrames.",
      h_setup: "4. Setup on Windows 11 (about 10 minutes)",
      setupSteps: [
        ["Prerequisites", "winget install Git, Node.js (≥ 22), FFmpeg; install Bun (≥ 1.0) for gstack."],
        ["gstack (~1 minute)", "In Claude Code: git clone --single-branch --depth 1 https://github.com/garrytan/gstack.git ~/.claude/skills/gstack && cd ~/.claude/skills/gstack && ./setup. Test with /office-hours."],
        ["HyperFrames", "claude plugin marketplace add heygen-com/hyperframes; claude plugin install hyperframes@hyperframes; restart Claude Code."],
        ["Doctor first", "npx hyperframes init agi-race-v2; npx hyperframes doctor. Pin the CLI version (the project used 0.8.79)."],
      ],
      setupNote: "Windows pitfall encountered: “'claude' is not recognized”. Fix by adding %LOCALAPPDATA%\\Microsoft\\WinGet\\Links to the user PATH and opening a new PowerShell.",
      h_diag: "5. What the V1 data said",
      diag: "V1 scored R 88 × A 90 × P 76, so B = 0.602. The views validated the topic (R × A resonance); 1.67 comments per 1,000 views showed conversion had not followed. A FFmpeg-measured Visual DNA then fixed what to keep and what to repair: 47 shots with a median of 1.08 s, the fastest cutting (0.95 s mean) just before the climax, a 1.5 s near-freeze followed by 0.84 s of black, and a 9:16 centre crop that loses the title, the wide ensemble, the final freeze and every subtitle.",
      h_detour: "6. The detour, and why it matters",
      detour: "The first sequel plan used Opus 5.5 to write prompts for a text-to-video model. On the home PC it stopped at its own entry gate, “FAIL”, because no reference images existed, and it refused to invent scores. After the pivot to HyperFrames, the C24 structure pilot proved the controlled layer (countdown correct at any seek time, black cut on frame 139, lint 0 errors, contrast 13/13) and also showed the limit: its R 0.82 and A 0.75 were held back by placeholder characters. V2 was the right next project because its pixels already existed.",
      h_changed: "7. What V2 changed",
      h_score: "8. The re-score, read honestly",
      score: "R rose from 88 to 92 (joke-first order, role tags, dead lines removed). A moved from 90 to 89: the structure fits Shorts better, but CTA length is untested. P rose from 76 to 94 (analyse → extract DNA → redesign → render). The strongest coupling is now R × P = 0.865, a production advantage that compounds across episodes. A +27.9 % structural gain is not a forecast of +27.9 % views.",
      h_next: "9. What must happen next",
      next: [
        "Freeze both uploads (youtube.com/shorts/mEztESwn7mI and youtu.be/6MnhRmSR_TA) for 24–72 hours.",
        "Pull Shorts metrics (views, shown in feed, stayed to watch, AVD, APV, likes, comments, shares, subscribers) and 16:9 metrics (impressions, CTR, AVD, retention, subscribers).",
        "Read three windows: 0–4.15 s (does the cold open stop the swipe?), ≈40 s (does “slow down → late entrant” lift attention?), last 8.6 s (does the end-card convert or cause exits?).",
        "If there is a retention cliff at the end-card and no subscriber lift, cut the hold from ≈2.5 s to ≈1–1.5 s in the next version.",
        "Compute an Observed RAP Score (proposed: stayed-to-watch %, APV, CCI with target > 2.5, subscribers per 1,000 views, Short APV ÷ master APV) and return it to the CSR-RAP agent before finalising the Episode 2 brief.",
      ],
      h_risks: "10. Limits and verification debt",
      risks: [
        ["No V2 analytics yet", "All V2 claims are structural."],
        ["Scores are judgements", "CSR-RAP rates design quality, not behaviour."],
        ["Mock screenshots", "The annotated screenshots are illustrative; replace before publishing a fork."],
        ["Determinism", "Renders are visually but not bit-for-bit identical (61/144 frames in C24)."],
        ["Generative layer", "Episode 2's faces, hands and keys remain untested."],
        ["Likeness", "The videos satirise real public figures; role tags reduce but do not remove this. Review platform policy each release."],
      ],
      h_appendix: "Appendix — annotated setup screenshots (illustrative mock-ups)",
      tableHead: ["Metric", "V1", "V2", "Assessment"],
      riskHead: ["Item", "Note"],
      stepHead: ["Step", "Action"],
      figPipe: "Figure 1 — Three layers, one loop",
      figTime: "Figure 2 — V1 vs V2 timing",
      figRap: "Figure 3 — CSR-RAP structural score, V1 vs V2",
      figMock: "Figure 4 — HyperFrames install and doctor (mock-up)",
      figMock2: "Figure 5 — Verification gates (mock-up; values from the C24 QA report)",
      footer: "Every number traces to docs/SOURCES.md",
    },
  },

  zh: {
    font: { head: "Microsoft YaHei", body: "Microsoft YaHei" },
    file: "gstack-tutorial-5",
    deck: {
      title: "从 YouTube 后台数据到一条重新设计的短视频",
      kicker: "gstack 教程 #5",
      subtitle: "CSR-RAP 智能体 × Claude Opus 5.5 × HyperFrames —— AGI Race V2 是如何做出来的",
      scope: "范围：已发布的 AGI Race Short 的 V2。Episode 2（碟中谍版）仍在制作中，本教程不作讲解。",
      date: "2026 年 9 月",
      exec: {
        title: "V2 的结构质量提升 27.9%；观众是否认同，仍是一个进行中的测试",
        cards: [
          { big: "0.602 → 0.770", label: "CSR-RAP 综合得分 B", text: "V1 验证了选题（R × A）；V2 加上了生产系统（R × P = 0.865）。" },
          { big: "4.15 秒", label: "完成钩子", text: "笑点先行、片名在后：前提在 Short 的 8.9% 时长内落地。" },
          { big: "1.67 → ?", label: "每千次播放评论数", text: "目标 > 2.5。在 72 小时真实数据回来之前，一切都未被证明。" },
        ],
      },
      system: {
        title: "真正的杠杆，是把工作拆分给三个职责不同的系统",
        takeaway: "决策（CSR-RAP）→ 制作（Opus 5.5 + gstack）→ 渲染（HyperFrames）→ 度量，然后循环。",
      },
      model: {
        title: "生成式 AI 制造“不确定的像素”，HyperFrames 控制“确定的信息”",
        left: "必须完全正确 → HyperFrames",
        leftItems: ["每个节拍的时间，精确到帧", "所有屏幕文字、字幕、角色标签", "每个镜头的 9:16 重新构图", "定格、切黑、结尾卡", "音效落点"],
        right: "允许变化 → 生成模型 / 原始素材",
        rightItems: ["写实人物与场景", "镜头内部的运动", "纹理与光影细节"],
        test: "Seek-safe 测试：渲染器直接跳到 t = 4.312 秒，这一帧还正确吗？",
        note: "V2 几乎不需要右栏的任何东西：它的像素在 V1 中已经存在。",
      },
      setup: {
        title: "整套工具链约 10 分钟装完，其中 gstack 只需 1 分钟",
        steps: [
          { n: "1", h: "前置软件", t: "Git · Node.js ≥ 22 · FFmpeg · Bun ≥ 1.0 · Claude Code", code: "winget install --id OpenJS.NodeJS -e" },
          { n: "2", h: "gstack（约 1 分钟）", t: "把 README 的一行命令粘贴进 Claude Code；用 /office-hours 测试", code: "git clone … garrytan/gstack.git ~/.claude/skills/gstack && ./setup" },
          { n: "3", h: "HyperFrames", t: "安装 Claude Code 插件并重启；/hyperframes 负责路由", code: "claude plugin install hyperframes@hyperframes" },
          { n: "4", h: "先跑 doctor", t: "设计之前先检查机器；锁定 CLI 版本", code: "npx hyperframes doctor" },
        ],
        pitfall: "实际踩坑：'claude' 无法识别 → 把 %LOCALAPPDATA%\\Microsoft\\WinGet\\Links 加入 PATH，再新开 PowerShell。",
      },
      shot: {
        title: "两条命令装好 HyperFrames；任何设计之前先跑 doctor",
        caption: "带标注的示意图（模拟画面），请替换为你本机的实际截图。",
      },
      diag: {
        title: "V1 证明了选题成立，但转化没有跟上播放量",
        stats: [
          { big: "58,736", label: "播放（频道首次破圈）" },
          { big: "98", label: "评论" },
          { big: "1.67", label: "CCI = 每千次播放评论数" },
        ],
        rows: [["R 商业共性", "88", "认知压缩：AI 竞赛变成一场沙漠赛车"],
               ["A 行业特性", "90", "热门话题、辨识度高的人物、契合 Shorts"],
               ["P 生产能力", "76", "因果链弱；9:16 下失效"],
               ["B = R × A × P", "0.602", "任何一层偏弱都会压低整体"]],
        head: ["层级", "得分", "诊断"],
      },
      dna: {
        title: "先测量 V1，才知道该保留什么、移动端到底哪里坏了",
        stats: [
          { big: "62.49 秒", label: "时长" },
          { big: "47", label: "个镜头（46 个硬切）" },
          { big: "1.08 秒", label: "镜头中位数；46 个中 20 个短于 1 秒" },
          { big: "0.95 秒", label: "最快区间的平均镜头，紧挨高潮之前" },
          { big: "1.5 秒 + 0.84 秒", label: "近似定格，随后黑场" },
          { big: "4", label: "处被 9:16 裁掉：片名、群像、最终定格、所有字幕" },
        ],
        note: "以上数值均由 Claude Code 中的 Opus 5.5 用 FFmpeg 实测（Episode1_Visual_DNA.md）。",
      },
      detour: {
        title: "只给别的生成器写 prompt 的智能体，本质上仍在赌博",
        quote: "“Entry gate: FAIL. Nothing has been generated yet… Numbers for frames nobody has generated would be invented.”",
        quoteBy: "Opus 5.5，文生视频路线，家中电脑",
        lessons: [
          { h: "闸门起作用了", t: "Opus 拒绝为不存在的素材打分。" },
          { h: "依赖关系错了", t: "整条流水线卡在最不可控的一步：生成人脸。" },
          { h: "转向证明了可控层", t: "C24 试制片：任意跳帧倒计时都正确；切黑落在第 139 帧；lint 0 错误；对比度 13/13。" },
          { h: "……也暴露了边界", t: "C24 得分 R 0.82、A 0.75：被占位人物拖累，而非结构。" },
        ],
      },
      playbook: {
        title: "七条 Shot Playbook 规则，把一天的错误变成永久约束",
        rules: [
          "先经 /hyperframes 路由；多场景 → /general-video",
          "设计前先跑 doctor、查看时间线",
          "先搜索组件库再动手；复用组件",
          "Seek-safe：禁止挂钟逻辑、Web Audio 图、冲突的 fromTo",
          "超过约 4 秒的停留加单向微动，禁止循环",
          "关键文字放在中间三分之一，保证 9:16 可见",
          "lint → check → snapshot → render → ffprobe，最后人眼确认",
        ],
        note: "渲染是视觉确定性的，而非逐比特一致：144 帧中 61 帧相同，其余 PSNR ≥ 50 dB。",
      },
      brief: {
        title: "V2 简报 = CSR-RAP 的改动清单 + 视觉 DNA 的保留清单",
        left: "改动（来自 CSR-RAP）",
        leftItems: ["以最强笑点冷开场", "片名砸出；约 4 秒内完成钩子", "角色标签取代“认脸”", "删除听不清的台词", "9:16 作为独立合成", "通往 Episode 2 的结尾卡"],
        right: "保留（来自视觉 DNA）",
        rightItems: ["快剪语法（镜头中位数约 1.08 秒）", "高潮前加速", "“慢下来”作为最大特写", "悬而未决的飞跃", "近似定格 → 黑场", "低饱和调色"],
        foot: "制作前：/office-hours → /plan-ceo-review（范围：HOLD，只做重剪）→ /plan-eng-review；制作后：/review。",
      },
      timeline: {
        title: "V2 在前 4.15 秒内交付了奇观、笑点和前提",
      },
      map: {
        title: "诊断指出的每一个 V1 弱点，V2 都有具体回应",
        head: ["指标", "V1", "V2", "判断"],
        rows: [
          ["主版本时长", "62.49 秒", "56.34 秒", "−9.8%"],
          ["Short 时长", "—", "46.54 秒", "比 V1 短 25.5%"],
          ["开场", "阵容 / 片名", "最强笑点先行", "明显升级"],
          ["钩子完成", "较慢", "4.15 秒", "更强"],
          ["角色理解", "依赖“认脸”", "明确的角色标签", "大幅升级"],
          ["9:16", "多处失效", "逐镜头重新构图", "大幅升级"],
          ["结尾", "悬而未决的飞跃", "飞跃 + Episode 2 桥段", "商业价值升级"],
          ["CTA 系统", "弱 / 泛泛", "TO BE CONTINUED → EP 2 → SUBSCRIBE", "明显升级"],
          ["生产方式", "视频生成", "可编程的 HyperFrames 重剪", "P 层显著提升"],
        ],
      },
      rap: {
        title: "最强的层级组合，从“选题”（R × A）转向“生产系统”（R × P）",
        cats: ["R", "A", "P", "B"],
        v1: [88, 90, 76, 60.2], v2: [92, 89, 94, 77.0],
        callouts: [
          { big: "+27.9%", t: "结构质量，B 0.602 → 0.770" },
          { big: "0.865", t: "R × P，现为最强耦合，会随每一集复利累积" },
          { big: "≠ 播放量", t: "这是设计得分，不是预测；A 层在真实数据回来之前仍是暂定" },
        ],
        chartTitle: "CSR-RAP 得分（×100）",
      },
      measure: {
        title: "两次上传冻结 72 小时，重点看留存曲线上的三个窗口",
        head: ["窗口", "问题", "若未通过"],
        rows: [
          ["0–4.15 秒", "冷开场能否阻止划走？", "测试另一个开场笑点"],
          ["约 40 秒", "“慢下来 → 迟到者”能否再拉高注意力？", "收紧其之前的升级段"],
          ["最后 8.6 秒", "结尾卡在增加订阅，还是导致退出？", "出现断崖且订阅无提升 → 停留 2.5 秒 → 1–1.5 秒"],
        ],
        q: "唯一的问题：HyperFrames 的包装，能否让同样的内容带来更好的观众行为？",
        obs: "观测型 RAP 得分（建议定义）：钩子 = 选择观看比例 · 留存 = 平均观看百分比 · 互动 = CCI（目标 > 2.5）· 每千次播放新增订阅 · 竖版优势 = Short ÷ 横版平均观看百分比",
      },
      limits: {
        title: "在“已证明”之前，还隔着四个局限",
        items: [
          { h: "尚无 V2 数据", t: "在 72 小时数据拉取之前，关于 V2 的结论都是结构性的。" },
          { h: "分数是判断", t: "CSR-RAP 评估的是设计质量，不是观众行为。" },
          { h: "生成层未验证", t: "Episode 2 的人脸、手部、钥匙仍是开放风险。" },
          { h: "讽刺真实人物", t: "角色标签降低对肖像的依赖；每次发布前复核平台政策。" },
        ],
      },
      os: {
        title: "同样九个步骤，可以重新设计任何一条 Short",
        steps: ["导出数据，计算 CCI", "CSR-RAP 诊断", "测量：视觉 DNA", "质疑：/office-hours", "给 Opus 5.5 下简报", "HyperFrames 制作 + 验证", "重新打分（设计）", "上传、冻结、度量 72 小时", "反馈到下一份简报"],
      },
      close: {
        title: "去度量，而不是再改片",
        text: "下一个决定属于观众数据，而不是又一次渲染。",
        links: ["仓库：TUTORIAL.md · TUTORIAL.zh.md · starter/prompts · docs/SOURCES.md", "gstack：github.com/garrytan/gstack", "HyperFrames：github.com/heygen-com/hyperframes"],
      },
      sources: "来源：docs/SOURCES.md",
    },
    memo: {
      title: "执行备忘录 —— gstack 教程 #5",
      subtitle: "从 YouTube 后台数据到一条重新设计的短视频：CSR-RAP × Claude Opus 5.5 × HyperFrames",
      meta: [["主题", "AGI Race V2 是如何做出来的，以及下一步必须做什么"], ["日期", "2026 年 9 月 29 日"], ["配套文件", "TUTORIAL.zh.md（完整教程）· 幻灯片 · starter/prompts"]],
      h_bottom: "1. 核心结论",
      bottom: [
        "真正的杠杆不是更好的 prompt，而是把工作拆分给三个职责不同的系统：CSR-RAP 智能体决定改什么，Claude Code 中的 Claude Opus 5.5（配合 gstack）把改动写出来，HyperFrames 以确定性方式渲染。",
        "V2 重新设计了已发布的 AGI Race Short（58,736 次播放、98 条评论）：以最强笑点开场，4.15 秒内完成钩子，用角色标签取代“认脸”，为 9:16 逐镜头重新导演，并以通往 Episode 2 的桥段收尾。横版 56.34 秒（−9.8%）；竖版 Short 46.54 秒（−25.5%）。",
        "CSR-RAP 给 V2 的结构质量打出 B = 0.770，V1 为 0.602（+27.9%）。这是设计得分。观众是否表现更好，仍是一个进行中的 A/B 测试，需要 72 小时真实数据来判定。",
      ],
      h_scope: "2. 范围",
      scope: "本备忘录只涵盖现有 AGI Race Short 的 V2。Episode 2（《OpenAI vs. Anthropic —— 碟中谍版》）仍在制作中，只在其试制片为生产系统提供经验时才被提及。",
      h_system: "3. 系统",
      system: "每一层只有一项职责，也有一件绝对不能做的事：策略层不能编造平台数据；智能体层不能只给别的生成器写 prompt；渲染层不能被要求凭空生成写实人物。决定分工的规则是 seek-safe 测试：渲染器直接跳到任意时刻，这一帧还正确吗？凡是必须完全正确的东西——时间、文字、角色标签、9:16 裁切、定格、结尾卡、音效——都放进 HyperFrames。",
      h_setup: "4. 在 Windows 11 上搭建（约 10 分钟）",
      setupSteps: [
        ["前置软件", "用 winget 安装 Git、Node.js（≥ 22）、FFmpeg；为 gstack 安装 Bun（≥ 1.0）。"],
        ["gstack（约 1 分钟）", "在 Claude Code 中执行：git clone --single-branch --depth 1 https://github.com/garrytan/gstack.git ~/.claude/skills/gstack && cd ~/.claude/skills/gstack && ./setup。用 /office-hours 测试。"],
        ["HyperFrames", "claude plugin marketplace add heygen-com/hyperframes；claude plugin install hyperframes@hyperframes；重启 Claude Code。"],
        ["先跑 doctor", "npx hyperframes init agi-race-v2；npx hyperframes doctor。锁定 CLI 版本（本项目为 0.8.79）。"],
      ],
      setupNote: "实际遇到的 Windows 坑：“'claude' 不是内部或外部命令”。把 %LOCALAPPDATA%\\Microsoft\\WinGet\\Links 加入用户 PATH，并新开 PowerShell 即可。",
      h_diag: "5. V1 数据说明了什么",
      diag: "V1 得分 R 88 × A 90 × P 76，B = 0.602。播放量验证了选题（R × A 共振）；每千次播放 1.67 条评论说明转化没有跟上。随后，经 FFmpeg 实测的视觉 DNA 明确了该保留什么、该修复什么：47 个镜头，中位数 1.08 秒；最快剪辑（平均 0.95 秒）紧挨高潮之前；1.5 秒近似定格后接 0.84 秒黑场；9:16 居中裁切会丢掉片名、群像远景、最终定格和所有字幕。",
      h_detour: "6. 走过的弯路，以及它为何重要",
      detour: "续集的第一版方案让 Opus 5.5 给文生视频模型写 prompt。在家中电脑上，它在自己设置的入口闸门处判定“FAIL”：没有参考图，也拒绝编造分数。转向 HyperFrames 后，C24 结构试制片证明了可控层（任意跳帧倒计时都正确，切黑落在第 139 帧，lint 0 错误，对比度 13/13），同时也暴露了边界：R 0.82 与 A 0.75 被占位人物拖累。V2 之所以是正确的下一步，是因为它的像素已经存在。",
      h_changed: "7. V2 改了什么",
      h_score: "8. 诚实地解读重新打分",
      score: "R 从 88 升至 92（笑点先行、角色标签、删除无效台词）。A 从 90 变为 89：结构更贴合 Shorts，但 CTA 长度尚未检验。P 从 76 升至 94（分析 → 提取 DNA → 重新设计 → 渲染）。最强耦合如今是 R × P = 0.865，这是一种会随每一集复利累积的生产优势。结构质量 +27.9% 并不等于播放量 +27.9%。",
      h_next: "9. 下一步必须做什么",
      next: [
        "两次上传（youtube.com/shorts/mEztESwn7mI 与 youtu.be/6MnhRmSR_TA）冻结 24–72 小时。",
        "拉取 Shorts 指标（播放、Feed 展示、选择观看比例、平均观看时长、平均观看百分比、点赞、评论、分享、订阅）与 16:9 指标（展示次数、点击率、平均观看时长、留存、订阅）。",
        "看三个窗口：0–4.15 秒（冷开场能否阻止划走？）、约 40 秒（“慢下来 → 迟到者”能否拉高注意力？）、最后 8.6 秒（结尾卡在转化还是导致退出？）。",
        "如果结尾卡处出现留存断崖且订阅没有提升，下一版把停留从约 2.5 秒缩短到约 1–1.5 秒。",
        "计算观测型 RAP 得分（建议定义：选择观看比例、平均观看百分比、CCI 目标 > 2.5、每千次播放新增订阅、Short ÷ 横版平均观看百分比），在定稿 Episode 2 简报前交回 CSR-RAP 智能体。",
      ],
      h_risks: "10. 局限与验证欠账",
      risks: [
        ["尚无 V2 数据", "所有关于 V2 的结论都是结构性的。"],
        ["分数是判断", "CSR-RAP 评估设计质量，而不是观众行为。"],
        ["示意截图", "带标注的截图为模拟画面；fork 公开发布前需替换。"],
        ["确定性", "渲染视觉一致但非逐比特一致（C24 中 144 帧有 61 帧相同）。"],
        ["生成层", "Episode 2 的人脸、手部、钥匙仍未验证。"],
        ["肖像", "视频讽刺真实公众人物；角色标签可降低但不能消除这一点。每次发布前复核平台政策。"],
      ],
      h_appendix: "附录 —— 带标注的安装截图（示意图）",
      tableHead: ["指标", "V1", "V2", "判断"],
      riskHead: ["事项", "说明"],
      stepHead: ["步骤", "操作"],
      figPipe: "图 1 —— 三层系统，一个闭环",
      figTime: "图 2 —— V1 与 V2 的时间结构",
      figRap: "图 3 —— CSR-RAP 结构得分：V1 与 V2",
      figMock: "图 4 —— 安装 HyperFrames 并运行 doctor（示意图）",
      figMock2: "图 5 —— 验证闸门（示意图；数值取自 C24 QA 报告）",
      footer: "每一个数字均可在 docs/SOURCES.md 中追溯",
    },
  },
};

module.exports = C;
